wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    code_path: code/test_model.py
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1680102616.427504
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 300
epoch:
  desc: null
  value: 4
loss:
  desc: null
  value: sparse_categorical_crossentropy
metric:
  desc: null
  value: accuracy
optimizer:
  desc: null
  value: adam
